import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const root=path.dirname(fileURLToPath(import.meta.url));
const env=Object.fromEntries((fs.existsSync(path.join(root,'.env'))?fs.readFileSync(path.join(root,'.env'),'utf8'):'').split(/\r?\n/).filter(x=>x&&!x.startsWith('#')).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)]}));
const setting=k=>process.env[k]||env[k];
const port=Number(setting('PORT')||3000),secret=setting('SESSION_SECRET')||'change-this-secret';
const databaseUrl=setting('DATABASE_URL');
if(!databaseUrl){console.error('Falta DATABASE_URL. Copia .env.example y levanta PostgreSQL con: npm run db:up');process.exit(1)}
const {Pool}=pg;
const pool=new Pool({connectionString:databaseUrl,ssl:setting('DATABASE_SSL')==='true'?{rejectUnauthorized:false}:false});
for(const dir of ['uploads','public'])fs.mkdirSync(path.join(root,dir),{recursive:true});
const query=(text,params=[])=>pool.query(text,params);
const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))};
const knownCountryCodes=new Set('AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' '));
const socialPreviewCrawler=req=>/(facebookexternalhit|facebot|whatsapp|telegrambot|twitterbot|linkedinbot|slackbot)/i.test(String(req.headers['user-agent']||''));
const publicAsset=pathname=>pathname.startsWith('/uploads/')||/\.(?:css|js|png|jpe?g|webp|svg|ico|json|webmanifest|map|woff2?)$/i.test(pathname);
const restrictedCountry=req=>{if(setting('NODE_ENV')!=='production')return false;const country=String(req.headers['cf-ipcountry']||'').trim().toUpperCase();return knownCountryCodes.has(country)&&country!=='PE'};
const countryUnavailable=res=>{const html='<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pronto estaremos en tu país | Fletop</title><style>body{min-height:100vh;margin:0;display:grid;place-items:center;background:radial-gradient(ellipse at 94% 0%,#d9d3ff,transparent 55%),radial-gradient(ellipse at 3% 100%,#cfe8ff,transparent 56%),#f8f9ff;color:#18212e;font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.notice{box-sizing:border-box;width:min(92vw,520px);padding:44px 36px;border:1px solid #dfe4ee;border-radius:24px;background:rgba(255,255,255,.86);box-shadow:0 20px 48px rgba(38,48,87,.12);text-align:center}.brand{display:inline-flex;align-items:center;gap:10px;margin-bottom:30px;font-size:21px;font-weight:800}.brand i{display:grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#3d43dc;color:#fff;font-style:normal;font-size:22px}.notice h1{margin:0;font-size:30px;letter-spacing:-.8px}.notice p{margin:14px 0 0;color:#657168;font-size:16px;line-height:1.55}@media(max-width:480px){.notice{padding:36px 24px}.notice h1{font-size:26px}}</style></head><body><main class="notice"><div class="brand"><i>↗</i>Fletop</div><h1>Pronto estaremos en tu país</h1><p>Fletop aún no está disponible en tu ubicación.</p></main></body></html>';res.writeHead(403,{'content-type':'text/html; charset=utf-8','cache-control':'no-store'});res.end(html)};
async function body(req){let data='';for await(const chunk of req)data+=chunk;if(!data)return {};try{return JSON.parse(data)}catch{return {}}}
const hash=password=>crypto.scryptSync(password,secret,32).toString('hex');
const token=id=>{const value=String(id),sig=crypto.createHmac('sha256',secret).update(value).digest('hex');return value+'.'+sig};
const cookie=(req,name)=>(req.headers.cookie||'').match(new RegExp('(?:^|;\\s*)'+name+'=([^;]+)'))?.[1];
async function user(req){const raw=cookie(req,'session');if(!raw)return null;const [id,sig]=raw.split('.'),expected=crypto.createHmac('sha256',secret).update(id||'').digest('hex');if(!id||!sig||sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;return (await query('SELECT id,name,email,phone,role,avatar,active,has_local_password FROM users WHERE id=$1 AND active=true',[id])).rows[0]||null}
const recordLogin=async id=>{const result=await query('UPDATE users SET last_login_at=now() WHERE id=$1 RETURNING last_login_at',[id]);if(result.rowCount!==1)throw Error('No se pudo registrar el inicio de sesión');return result.rows[0].last_login_at};
async function requireUser(req,res){const account=await user(req);if(!account){json(res,401,{error:'Debes iniciar sesión'});return null}return account}
const listing=row=>({...row,images:Array.isArray(row.images)?row.images:JSON.parse(row.images||'[]')});
function saveImage(data){const match=String(data||'').match(/^data:(image\/(?:png|jpeg|webp));base64,(.+)$/);if(!match)return null;const file=Date.now()+'-'+crypto.randomUUID()+'.'+match[1].split('/')[1].replace('jpeg','jpg');fs.writeFileSync(path.join(root,'uploads',file),Buffer.from(match[2],'base64'));return '/uploads/'+file}
async function schema(){
 await query(`CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password TEXT,
 phone TEXT,role TEXT NOT NULL DEFAULT 'user' CHECK(role IN ('user','admin')),avatar TEXT,
 active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS listings (
 id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 origin TEXT NOT NULL,destination TEXT NOT NULL,weight TEXT NOT NULL,title TEXT NOT NULL,
 details TEXT NOT NULL DEFAULT '',phone TEXT NOT NULL,whatsapp TEXT,images JSONB NOT NULL DEFAULT '[]'::jsonb,
 active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS reports (
 id BIGSERIAL PRIMARY KEY,listing_id BIGINT NOT NULL REFERENCES listings(id) ON DELETE CASCADE,
 reporter_id BIGINT REFERENCES users(id) ON DELETE SET NULL,reason TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS password_resets (
 id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
 token_hash TEXT NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ);
 CREATE INDEX IF NOT EXISTS listings_route_idx ON listings(origin,destination);
 CREATE INDEX IF NOT EXISTS listings_active_created_idx ON listings(active,created_at DESC);`);
 await query(`ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
 ALTER TABLE users ALTER COLUMN password DROP NOT NULL;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS has_local_password BOOLEAN NOT NULL DEFAULT true;
 ALTER TABLE users ADD COLUMN IF NOT EXISTS google_subject TEXT;
 CREATE UNIQUE INDEX IF NOT EXISTS users_google_subject_unique ON users(google_subject) WHERE google_subject IS NOT NULL;`);
 const adminEmail=(setting('ADMIN_EMAIL')||'').toLowerCase(),adminPass=setting('ADMIN_PASSWORD');
 if(adminEmail&&adminPass){const existing=(await query('SELECT id FROM users WHERE email=$1',[adminEmail])).rows[0];if(existing)await query(`UPDATE users SET role='admin',password=$1,has_local_password=true,active=true WHERE id=$2`,[hash(adminPass),existing.id]);else await query(`INSERT INTO users(name,email,password,role) VALUES($1,$2,$3,'admin')`,['Administrador',adminEmail,hash(adminPass)])}
}
const appRoute=pathname=>/^\/(?:|login|register|olvido|restablecer|publish|publicar|profile|perfil|admin|buscar|como-funciona|about|documentation|papers|press|terms|privacy|data|cookies|listing\/\d+|edit\/\d+|item\/[^/]+-\d+)\/?$/.test(pathname);
const mimeType=file=>({'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'})[path.extname(file).toLowerCase()]||'application/octet-stream';
const escapeHtml=value=>String(value||'').replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const compactText=(value,limit=220)=>String(value||'').replace(/\s+/g,' ').trim().slice(0,limit);
const publicOrigin=req=>{const configured=setting('PUBLIC_BASE_URL');if(configured){try{const url=new URL(configured);url.protocol='https:';url.pathname='';url.search='';url.hash='';return url.toString().replace(/\/$/,'')}catch{}}const host=String(req.headers.host||'www.fletop.com').replace(/[^a-zA-Z0-9.:-]/g,'')||'www.fletop.com';return 'https://'+host};
const absoluteAssetUrl=(req,asset)=>new URL(asset,publicOrigin(req)+'/').toString();
const publicFile=(req,res)=>{let urlPath=decodeURIComponent(new URL(req.url,'http://x').pathname),status=200;if(appRoute(urlPath)){urlPath='/index.html'}else if(!path.extname(urlPath)){urlPath='/index.html'}const file=path.join(root,'public',urlPath);if(!file.startsWith(path.join(root,'public'))||!fs.existsSync(file))return false;const dynamicAsset=/\.(html|css|js)$/.test(urlPath);res.writeHead(status,{'content-type':mimeType(file),'cache-control':dynamicAsset?'no-cache':'public, max-age=3600'});fs.createReadStream(file).pipe(res);return true};
async function itemPage(req,res,id,pathname){const row=(await query('SELECT id,title,details,origin,destination,images FROM listings WHERE id=$1',[id])).rows[0];if(!row)return false;const images=listing(row).images,storedImage=images.find(image=>typeof image==='string'&&/^\/uploads\/[a-zA-Z0-9._-]+$/.test(image)),imagePath=storedImage||'/og-fletop.png',canonical=publicOrigin(req)+pathname,title=compactText(row.title,110)||'Carga disponible en Fletop',route=[compactText(row.origin,80),compactText(row.destination,80)].filter(Boolean).join(' → '),description=compactText([title,route,compactText(row.details,150)].filter(Boolean).join(' · '),230),image=absoluteAssetUrl(req,imagePath),imageType=mimeType(imagePath),meta='<meta property="og:title" content="'+escapeHtml(title)+'"/><meta property="og:description" content="'+escapeHtml(description)+'"/><meta property="og:image" content="'+escapeHtml(image)+'"/><meta property="og:image:secure_url" content="'+escapeHtml(image)+'"/><meta property="og:image:type" content="'+escapeHtml(imageType)+'"/><meta property="og:url" content="'+escapeHtml(canonical)+'"/><meta property="og:type" content="website"/><meta property="og:site_name" content="Fletop"/><meta name="twitter:card" content="summary_large_image"/><meta name="twitter:title" content="'+escapeHtml(title)+'"/><meta name="twitter:description" content="'+escapeHtml(description)+'"/><meta name="twitter:image" content="'+escapeHtml(image)+'"/><link rel="canonical" href="'+escapeHtml(canonical)+'"/>',template=fs.readFileSync(path.join(root,'public','index.html'),'utf8'),html=template.replace('<title>Fletop | Cargas para tu camión</title>','<title>'+escapeHtml(title)+' | Fletop</title>').replace('<meta name="description" content="Encuentra cargas directas para tu ruta con Fletop."/>','<meta name="description" content="'+escapeHtml(description)+'"/>').replace('<!-- FLETOP_OG -->',meta);res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-cache'});res.end(html);return true}
const adminOnly=async(req,res)=>{const account=await requireUser(req,res);if(!account)return null;if(account.role!=='admin'){json(res,403,{error:'Solo administración'});return null}return account};
async function server(req,res){try{const url=new URL(req.url,'http://x'),p=url.pathname;
 if(restrictedCountry(req)){const itemPreview=/^\/item\/[^/]+-\d+\/?$/.test(p);if(p.startsWith('/api/'))return json(res,403,{error:'Fletop aún no está disponible en tu país'});if(!publicAsset(p)&&!(itemPreview&&socialPreviewCrawler(req))){countryUnavailable(res);return}}
 if(req.method==='GET'&&p==='/auth/google'){const clientId=setting('GOOGLE_CLIENT_ID'),clientSecret=setting('GOOGLE_CLIENT_SECRET');if(!clientId||!clientSecret){res.writeHead(302,{location:'/login?google=missing'});res.end();return}const state=crypto.randomBytes(24).toString('hex'),proto=req.headers['x-forwarded-proto']||'http',base=proto+'://'+req.headers.host,params=new URLSearchParams({client_id:clientId,redirect_uri:base+'/auth/google/callback',response_type:'code',scope:'openid email profile',state,prompt:'select_account'});res.writeHead(302,{'set-cookie':'oauth_state='+state+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=600',location:'https://accounts.google.com/o/oauth2/v2/auth?'+params});res.end();return}
 if(req.method==='GET'&&p==='/auth/google/callback'){const state=url.searchParams.get('state'),code=url.searchParams.get('code'),saved=cookie(req,'oauth_state'),clientId=setting('GOOGLE_CLIENT_ID'),clientSecret=setting('GOOGLE_CLIENT_SECRET');if(!state||!code||state!==saved||!clientId||!clientSecret){res.writeHead(302,{location:'/login?google=error'});res.end();return}try{const proto=req.headers['x-forwarded-proto']||'http',base=proto+'://'+req.headers.host,exchange=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:clientId,client_secret:clientSecret,redirect_uri:base+'/auth/google/callback',grant_type:'authorization_code'})}),tokens=await exchange.json();if(!exchange.ok)throw Error('token');const profileResponse=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{authorization:'Bearer '+tokens.access_token}}),profile=await profileResponse.json();if(!profileResponse.ok||!profile.email_verified||!profile.sub)throw Error('profile');const email=String(profile.email).toLowerCase(),subject=String(profile.sub),bySubject=(await query('SELECT id,active FROM users WHERE google_subject=$1',[subject])).rows[0];let account=bySubject;if(!account){const byEmail=(await query('SELECT id,active,google_subject FROM users WHERE email=$1',[email])).rows[0];if(byEmail){if(!byEmail.active)throw Error('inactive');if(byEmail.google_subject&&byEmail.google_subject!==subject)throw Error('identity');const linked=await query('UPDATE users SET google_subject=$1 WHERE id=$2 AND google_subject IS NULL RETURNING id,active',[subject,byEmail.id]);if(!linked.rowCount)throw Error('identity');account=linked.rows[0]}else{account=(await query('INSERT INTO users(name,email,password,role,has_local_password,google_subject) VALUES($1,$2,NULL,$3,false,$4) RETURNING id,active',[profile.name||email.split('@')[0],email,email===(setting('ADMIN_EMAIL')||'').toLowerCase()?'admin':'user',subject])).rows[0]}}if(!account||!account.active)throw Error('inactive');await recordLogin(account.id);res.writeHead(302,{'set-cookie':['session='+token(account.id)+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000','oauth_state=; Path=/; Max-Age=0'],location:'/perfil'});res.end()}catch{res.writeHead(302,{location:'/login?google=error'});res.end()}return}
 if(req.method==='GET'&&p.startsWith('/uploads/')){const file=path.join(root,p);if(!file.startsWith(path.join(root,'uploads'))||!fs.existsSync(file))return json(res,404,{error:'No encontrado'});res.writeHead(200,{'content-type':mimeType(file),'cache-control':'public, max-age=3600'});fs.createReadStream(file).pipe(res);return}
 const itemMatch=p.match(/^\/item\/[^/]+-(\d+)\/?$/);if(req.method==='GET'&&itemMatch&&await itemPage(req,res,itemMatch[1],p))return;
 if(req.method==='GET'&&p==='/api/me')return json(res,200,{user:await user(req)});
 if(req.method==='GET'&&p==='/api/listings'){const origin=url.searchParams.get('origin')||'',destination=url.searchParams.get('destination')||'',term=url.searchParams.get('q')||'';const params=[],where=['l.active=true'];if(origin){params.push('%'+origin+'%');where.push('l.origin ILIKE $'+params.length)}if(destination){params.push('%'+destination+'%');where.push('l.destination ILIKE $'+params.length)}if(term){params.push('%'+term+'%');where.push('(l.title ILIKE $'+params.length+' OR l.details ILIKE $'+params.length+')')}const rows=(await query(`SELECT l.*,u.name user_name,u.avatar user_avatar FROM listings l JOIN users u ON u.id=l.user_id WHERE ${where.join(' AND ')} ORDER BY l.created_at DESC`,params)).rows;return json(res,200,{listings:rows.map(listing)})}
 if(req.method==='GET'&&/^\/api\/listings\/\d+$/.test(p)){const row=(await query('SELECT l.*,u.name user_name,u.avatar user_avatar FROM listings l JOIN users u ON u.id=l.user_id WHERE l.id=$1',[p.split('/').pop()])).rows[0];return row?json(res,200,{listing:listing(row)}):json(res,404,{error:'No encontrado'})}
 if(req.method==='GET'&&p==='/api/my-listings'){const account=await requireUser(req,res);if(!account)return;const rows=(await query('SELECT l.*,u.name user_name,u.avatar user_avatar FROM listings l JOIN users u ON u.id=l.user_id WHERE l.user_id=$1 ORDER BY l.created_at DESC',[account.id])).rows;return json(res,200,{listings:rows.map(listing)})}
 if(req.method==='POST'&&p==='/api/login'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||password.length<6)return json(res,400,{error:'Ingresa un correo válido y una contraseña de 6 caracteres mínimo'});let account=(await query('SELECT * FROM users WHERE email=$1',[email])).rows[0];if(account){if(!account.active)return json(res,401,{error:'Correo o contraseña incorrectos, o cuenta desactivada'});if(!account.has_local_password||!account.password)return json(res,401,{error:'Esta cuenta usa Google. Continúa con Google o restablece tu contraseña para crear una contraseña local.'});if(hash(password)!==account.password)return json(res,401,{error:'Correo o contraseña incorrectos, o cuenta desactivada'})}else{try{const role=email===(setting('ADMIN_EMAIL')||'').toLowerCase()?'admin':'user';account=(await query('INSERT INTO users(name,email,password,role,has_local_password) VALUES($1,$2,$3,$4,true) RETURNING *',[email.split('@')[0],email,hash(password),role])).rows[0]}catch(error){if(error.code==='23505')return json(res,401,{error:'Correo o contraseña incorrectos, o cuenta desactivada'});throw error}}await recordLogin(account.id);res.writeHead(200,{'set-cookie':'session='+token(account.id)+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000','content-type':'application/json'});res.end('{"ok":true}');return}
 if(req.method==='POST'&&p==='/api/password/forgot'){const b=await body(req),email=String(b.email||'').trim().toLowerCase(),account=(await query('SELECT id,email FROM users WHERE email=$1 AND active=true',[email])).rows[0];if(!account)return json(res,200,{ok:true});const raw=crypto.randomBytes(32).toString('hex'),tokenHash=crypto.createHash('sha256').update(raw).digest('hex'),expires=new Date(Date.now()+60*60*1000),proto=req.headers['x-forwarded-proto']||'http',base=proto+'://'+req.headers.host,resetLink=base+'/restablecer?token='+raw;await query('UPDATE password_resets SET used_at=now() WHERE user_id=$1 AND used_at IS NULL',[account.id]);await query('INSERT INTO password_resets(user_id,token_hash,expires_at) VALUES($1,$2,$3)',[account.id,tokenHash,expires]);const resend=setting('RESEND_API_KEY'),from=setting('MAIL_FROM');if(resend&&from){const sent=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:'Bearer '+resend,'content-type':'application/json'},body:JSON.stringify({from,to:[account.email],subject:'Recupera tu contraseña de Fletop',html:'<p>Solicitaste restablecer tu contraseña.</p><p><a href="'+resetLink+'">Crear una nueva contraseña</a></p><p>Este enlace vence en una hora.</p>'})});if(!sent.ok)console.error('No se pudo enviar correo de recuperación',await sent.text())}else console.log('Enlace de recuperación (configura RESEND_API_KEY y MAIL_FROM en producción): '+resetLink);return json(res,200,{ok:true,reset_link:setting('NODE_ENV')==='production'?undefined:resetLink})}
 if(req.method==='POST'&&p==='/api/password/reset'){const b=await body(req),raw=String(b.token||''),password=String(b.password||'');if(raw.length<32||password.length<6)return json(res,400,{error:'El enlace no es válido o la contraseña es muy corta'});const tokenHash=crypto.createHash('sha256').update(raw).digest('hex'),reset=(await query('SELECT * FROM password_resets WHERE token_hash=$1 AND used_at IS NULL AND expires_at>now() ORDER BY id DESC LIMIT 1',[tokenHash])).rows[0];if(!reset)return json(res,400,{error:'El enlace expiró o ya fue utilizado'});await query('UPDATE users SET password=$1,has_local_password=true WHERE id=$2',[hash(password),reset.user_id]);await query('UPDATE password_resets SET used_at=now() WHERE id=$1',[reset.id]);return json(res,200,{ok:true})}
 if(req.method==='POST'&&p==='/api/logout'){res.writeHead(200,{'set-cookie':'session=; Path=/; Max-Age=0','content-type':'application/json'});res.end('{"ok":true}');return}
 if(req.method==='PUT'&&p==='/api/profile'){const account=await requireUser(req,res);if(!account)return;const b=await body(req),name=String(b.name||'').trim(),email=String(b.email||account.email).trim().toLowerCase();if(!name)return json(res,400,{error:'El nombre es obligatorio'});if(!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Ingresa un correo válido'});let avatar=account.avatar;if(b.avatar)avatar=saveImage(b.avatar)||avatar;let password=null;if(b.newPassword){const stored=(await query('SELECT password,has_local_password FROM users WHERE id=$1',[account.id])).rows[0];if(stored.has_local_password&&(!b.currentPassword||hash(b.currentPassword)!==stored.password))return json(res,400,{error:'La contraseña actual no es correcta'});if(String(b.newPassword).length<6)return json(res,400,{error:'La nueva contraseña debe tener al menos 6 caracteres'});password=hash(b.newPassword)}try{await query(password?'UPDATE users SET name=$1,email=$2,avatar=$3,password=$4,has_local_password=true WHERE id=$5':'UPDATE users SET name=$1,email=$2,avatar=$3 WHERE id=$4',password?[name,email,avatar,password,account.id]:[name,email,avatar,account.id]);return json(res,200,{ok:true})}catch(error){return json(res,error.code==='23505'?409:500,{error:error.code==='23505'?'Ese correo ya está registrado':'No se pudo actualizar la cuenta'})}}
 if(req.method==='POST'&&p==='/api/listings'){const account=await requireUser(req,res);if(!account)return;const b=await body(req);if(!b.origin||!b.destination||!b.weight||!b.title||!b.phone)return json(res,400,{error:'Completa los campos obligatorios'});if(b.origin===b.destination)return json(res,400,{error:'Origen y destino deben ser distintos'});const images=(b.images||[]).slice(0,4).map(saveImage).filter(Boolean);await query('INSERT INTO listings(user_id,origin,destination,weight,title,details,phone,whatsapp,images) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[account.id,b.origin,b.destination,b.weight,b.title,b.details||'',b.phone,b.whatsapp||b.phone,JSON.stringify(images)]);return json(res,201,{ok:true})}
 if(req.method==='PUT'&&/^\/api\/listings\/\d+$/.test(p)){const account=await requireUser(req,res);if(!account)return;const id=p.split('/').pop(),b=await body(req),current=(await query('SELECT * FROM listings WHERE id=$1',[id])).rows[0];if(!current||(String(current.user_id)!==String(account.id)&&account.role!=='admin'))return json(res,403,{error:'Sin permiso'});const origin=b.origin||current.origin,destination=b.destination||current.destination;if(origin===destination)return json(res,400,{error:'Origen y destino deben ser distintos'});const images=Array.isArray(b.images)?b.images:current.images;for(const item of (b.newImages||[]).slice(0,4-images.length)){const image=saveImage(item);if(image)images.push(image)}await query('UPDATE listings SET origin=$1,destination=$2,title=$3,details=$4,phone=$5,whatsapp=$6,images=$7,active=$8 WHERE id=$9',[origin,destination,b.title||current.title,b.details??current.details,b.phone||current.phone,b.whatsapp||current.whatsapp,JSON.stringify(images),b.active===false?false:current.active,id]);return json(res,200,{ok:true})}
 if(req.method==='POST'&&/^\/api\/listings\/\d+\/report$/.test(p)){const b=await body(req),account=await user(req);await query('INSERT INTO reports(listing_id,reporter_id,reason) VALUES($1,$2,$3)',[p.split('/')[3],account?.id||null,b.reason||'Contenido inapropiado']);return json(res,201,{ok:true})}
 if(req.method==='GET'&&p==='/api/admin/stats'){if(!await adminOnly(req,res))return;const [users,listings,reports,recent]=await Promise.all([query('SELECT count(*)::int n FROM users'),query('SELECT count(*)::int n FROM listings'),query('SELECT count(*)::int n FROM reports'),query('SELECT l.*,u.name user_name,u.avatar user_avatar FROM listings l JOIN users u ON u.id=l.user_id ORDER BY l.created_at DESC LIMIT 10')]);return json(res,200,{users:users.rows[0].n,listings:listings.rows[0].n,reports:reports.rows[0].n,recent:recent.rows.map(listing)})}
 if(req.method==='GET'&&p==='/api/admin/reports'){if(!await adminOnly(req,res))return;const rows=(await query('SELECT r.*,l.title,l.active,l.images,l.origin,l.destination FROM reports r JOIN listings l ON l.id=r.listing_id ORDER BY r.created_at DESC')).rows;return json(res,200,{reports:rows})}
 if(req.method==='GET'&&p==='/api/admin/users'){if(!await adminOnly(req,res))return;const rows=(await query('SELECT id,name,email,role,avatar,active,created_at,last_login_at,google_subject IS NOT NULL AS google_connected FROM users ORDER BY created_at DESC')).rows;return json(res,200,{users:rows})}
 if(req.method==='GET'&&/^\/api\/admin\/users\/\d+\/listings$/.test(p)){if(!await adminOnly(req,res))return;const id=p.split('/')[4],rows=(await query('SELECT l.*,u.name user_name,u.avatar user_avatar FROM listings l JOIN users u ON u.id=l.user_id WHERE l.user_id=$1 ORDER BY l.created_at DESC',[id])).rows;return json(res,200,{listings:rows.map(listing)})}
 if(req.method==='PUT'&&/^\/api\/admin\/users\/\d+$/.test(p)){if(!await adminOnly(req,res))return;const b=await body(req),id=p.split('/').pop(),target=(await query('SELECT * FROM users WHERE id=$1',[id])).rows[0];if(!target)return json(res,404,{error:'Usuario no encontrado'});if(b.role&&b.role!=='user'&&b.role!=='admin')return json(res,400,{error:'Rol inválido'});let avatar=target.avatar;if(b.avatar)avatar=saveImage(b.avatar)||avatar;const password=b.newPassword?hash(b.newPassword):target.password,hasLocalPassword=b.newPassword?true:target.has_local_password;await query('UPDATE users SET name=$1,role=$2,avatar=$3,active=$4,password=$5,has_local_password=$6 WHERE id=$7',[String(b.name||target.name).trim(),b.role||target.role,avatar,b.active===false?false:true,password,hasLocalPassword,id]);return json(res,200,{ok:true})}
 if(req.method==='GET'&&p==='/api/admin/listings'){if(!await adminOnly(req,res))return;const city=url.searchParams.get('city')||'',params=city?['%'+city+'%']:[],clause=city?'WHERE l.origin ILIKE $1 OR l.destination ILIKE $1':'';const rows=(await query('SELECT l.*,u.name user_name,u.avatar user_avatar FROM listings l JOIN users u ON u.id=l.user_id '+clause+' ORDER BY l.created_at DESC',params)).rows;return json(res,200,{listings:rows.map(listing)})}
 if(req.method==='PUT'&&/^\/api\/admin\/listings\/\d+$/.test(p)){if(!await adminOnly(req,res))return;const b=await body(req);await query('UPDATE listings SET active=$1 WHERE id=$2',[b.active===false?false:true,p.split('/').pop()]);return json(res,200,{ok:true})}
 if(req.method==='DELETE'&&/^\/api\/admin\/listings\/\d+$/.test(p)){if(!await adminOnly(req,res))return;await query('DELETE FROM listings WHERE id=$1',[p.split('/').pop()]);return json(res,200,{ok:true})}
 if(req.method==='GET'&&publicFile(req,res))return;json(res,404,{error:'No encontrado'});
}catch(error){console.error(error);json(res,500,{error:'Ocurrió un error en el servidor'})}}
await schema();
http.createServer(server).listen(port,'127.0.0.1',()=>console.log('Fletop disponible en http://localhost:'+port));
